attributes:
  ART.-NO.:
    0: '11653951'
    1: '11653950'
  BAR:
    0: 6.0-8.0
    1: 4.0-6.5
  COLOUR:
    0: Black
    1: Black
  COMPOUND:
    0: Addix Race
    1: Addix Race
  DIAMETER:
    0: 20"
    1: 26"
  EPI:
    0: '127'
    1: '127'
  ETRTO:
    0: 28-406
    1: 28-559
  LOAD:
    0: 70 kg
    1: 75 kg
  PSI:
    0: 85-115
    1: 55-95
  SEAL:
    0: TLE
    1: TLE
  SIZE:
    0: 20x1.10
    1: 26x1.10
  VERSION:
    0: Evolution
    1: Evolution
  g:
    0: '205'
    1: '275'
  "\u20AC":
    0: 69,90
    1: 69,90
name: SCHWALBE PRO ONE TLE
product_category: ''
variant: "Evolution Line, Faltreifen \u2013 HS 462"
versions:
  Evolution:
    Grip: asdf
    Haltbarkeit: ''
    Pannenschutz: ''
    Rollwiderstand: ''
    Souplesse: ''
  sd:
    Grip: hj
    Haltbarkeit: ''
    Pannenschutz: ''
    Rollwiderstand: ''
    Souplesse: ''
---
attributes: {}
name: neu
product_category: ''
variant: ''
versions: {}
