attributes:
  0:
    0: null
    1: 28-406
    2: 28-559
  1:
    0: SIZE
    1: 20x1.10
    2: 26x1.10
  2:
    0: VERSION
    1: Evolution
    2: Evolution
  3:
    0: SEAL
    1: TLE
    2: TLE
  4:
    0: E-BIKE
    1: .nan
    2: .nan
  5:
    0: INDEX
    1: .nan
    2: .nan
  6:
    0: COMPOUND
    1: .nan
    2: .nan
  7:
    0: COLOUR
    1: Black
    2: Black
  8:
    0: BAR
    1: 6.0-8.0
    2: 4.0-6.5
  9:
    0: PSI
    1: 85-115
    2: 55-95
  10:
    0: g
    1: '205'
    2: '275'
  11:
    0: EPI
    1: '127'
    2: '127'
  12:
    0: LOAD
    1: 70 kg
    2: 75 kg
  13:
    0: ART.-NO.
    1: '11653951'
    2: '11653950'
name: Better Name
product_category: ''
variant: ''
versions: {}
---
attributes: {}
name: modify name
product_category: ''
variant: ''
versions: {}
